base/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('files/<str:choice>', views.files, name='files'),
    path('profile/', views.profile, name='profile'),
    path('blog/<int:choice>', views.blog, name='blog'),
    path('post_detail/<slug:slug>/', views.post_detail, name='post_detail'),
]

blog/urls.py
from django.contrib import admin
import os
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

STATUS = (
    (0,"Daily post"),
    (1,"Good posts"),
    (2,"Just thinking"),
    (3,"Final Destination"),
    (4,"Draft"),

)

class Post(models.Model):
    title = models.CharField(max_length = 200, unique = True)
    slug = models.SlugField(max_length = 200, unique = True)
    updated_on = models.DateTimeField(auto_now = True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add = True)
    status = models.IntegerField(choices = STATUS, default = 0)
    image = models.ImageField(default = None, upload_to = 'post_image', blank = True, null = True)
    file = models.FileField(upload_to = "files", blank = True, null = True, default = None)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class Music(models.Model):
    name = models.CharField(max_length = 200)
    artist = models.CharField(max_length = 200, blank = True, null = True)
    image = models.ImageField(default = 'music.png', upload_to = 'post_image', blank = True, null = True)
    file = models.FileField(upload_to = "Music", default = None)
    lyrics = models.TextField(blank = True, null = True)

    def __str__(self):
        return self.name

class File(models.Model):
    name = models.CharField(max_length = 200, blank= True, null= True)
    file = models.FileField(upload_to = "File", default= None)

    def __str__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(max_length = 200, blank= True, null= True)
    image = models.ImageField(upload_to = "Image", default= None)

base/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from .models import Post, Music, Image, File

def home(request):
	context = {}
	try:
		post1 = get_object_or_404(Post, slug='start')
		post2 = get_object_or_404(Post, slug='pin')

		posts = [post1, post2]
		context = {'posts': posts}

	except Exception as e:
		pass
	
	musics = Music.objects.all()[:3]
	context.update({'musics': musics})

	return render(request, 'base/home.html',context= context)

def profile(request):
	return render(request, 'base/profile.html')

def files(request, choice):
	print(choice)
	if choice == 'all':
		musics = Music.objects.all()[:3]
		images = Image.objects.all()[:3]
		files = File.objects.all()[:5]

		context = {'images': images, 'musics': musics, 'files': files, 'choice': choice.capitalize()}
	
	elif choice == 'musics':
		musics = Music.objects.all()
		context = {'musics': musics, 'choice': choice.capitalize()}
	
	elif choice == 'images':
		images = Image.objects.all()
		context = {'images': images, 'choice': choice.capitalize()}

	elif choice == 'files':
		files = File.objects.all()
		context = {'files': files, 'choice': choice.capitalize()}
	
	return render(request, 'base/files.html', context)

def blog(request, choice):
	if choice == 5:
		posts = Post.objects.all().order_by('-created_on')
	else:
		posts = Post.objects.filter(status=choice).order_by('-created_on')

	return render(request, 'base/blog.html', context={'posts': posts, 'choice': choice})

def post_detail(request, slug):
	post = get_object_or_404(Post)
	return render(request, 'base/post_detail.html', context = {'post': post})




# Create your views here.

base/templates/base/blog.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static 'base/bash.png' %}">
	<title>{{ type }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
</script>

<style type="text/css">
	@media only screen and (min-width: 768px) {
		.grid-right {
			width: 70%;
		}

		.grid-left {
			width: 30%;
			padding-right: 10px;
		}
	}

	@media only screen and (max-width: 768px) {
		.grid-right {
			width: 100%;
		}

		.grid-left {
			width: 100%;
		}
	}
</style>


<body class="container mt-3 mb-3">
	<ul class="nav nav-pills nav-fill">
	  <li class="nav-item">
	    <a class="nav-link" aria-current="page" href="{% url 'base:home' %}">Home</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link active" href="{% url 'base:blog' 5 %}">Blog</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'base:profile' %}">Profile</a>
	  </li>
	  <li class="nav-item">
	    <a href="{% url 'base:files' 'all' %}" class="nav-link">Files</a>
	  </li>
	</ul><br>



	<div class="">
		<div class="float-start grid-left">
			<ul class="list-group mb-2">
				{% if choice == 5 %}
					<a href="{% url 'base:blog' 5 %}" class="list-group-item active" aria-current="true">All posts</a>
				{% else %}
					<a href="{% url 'base:blog' 5 %}" class="list-group-item " aria-current="true">All posts</a>
				{% endif %}

				{% if choice == 0 %}
					<a href="{% url 'base:blog' 0 %}" class="list-group-item active" aria-current="true">Daily post</a>
				{% else %}
					<a href="{% url 'base:blog' 0 %}" class="list-group-item " aria-current="true">Daily post</a>
				{% endif %}

				{% if choice == 1 %}
					<a href="{% url 'base:blog' 1 %}" class="list-group-item active" aria-current="true">Good posts</a>
				{% else %}
					<a href="{% url 'base:blog' 1 %}" class="list-group-item " aria-current="true">Good posts</a>
				{% endif %}

				{% if choice == 2 %}
					<a href="{% url 'base:blog' 2 %}" class="list-group-item active" aria-current="true">Just Thinking !</a>
				{% else %}
					<a href="{% url 'base:blog' 2 %}" class="list-group-item " aria-current="true">Just Thinking !</a>
				{% endif %}
				
				{% if choice == 3 %}
					<a href="{% url 'base:blog' 3 %}" class="list-group-item active" aria-current="true">Final Destination</a>
				{% else %}
					<a href="{% url 'base:blog' 3 %}" class="list-group-item " aria-current="true">Final Destination</a>
				{% endif %}
			</ul>
			
		</div>

		<div class="float-start grid-right">
		{% if posts %}
			{% for post in posts %}
				<div class="card rounded mb-2">
				  <div class="p-3">
				    <a style="text-decoration-line: none" href="{% url 'base:post_detail' post.slug  %}" data-bs-toggle="modal" data-bs-target="#exampleModal{{ post.id }}"><h5 class="text-end">{{ post.title }}</h5></a>
				    <p class="text-end">{{ post.content | slice:":500" }}</p>
				  </div>

					<!-- Modal -->
					<div class="modal fade" id="exampleModal{{ post.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
					  <div class="modal-dialog">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h1 class="modal-title float-center fs-5" id="exampleModalLabel"><h5 class="text-center">{{ post.title }}</h5></h1>
					        <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
					      </div>
					      <div class="modal-body">
					        <div class="p-3">
							    <a style="text-decoration-line: none" href="{% url 'base:post_detail' post.slug  %}" ></a>
							    <p class="text-end">{{ post.content }}</p>
							  </div>
					      </div>
					      {% if post.image or post.file %}
						      <div class="modal-footer">
						      	<a style="text-decoration-line: none;" href="{{ post.file.url }}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-folder" viewBox="0 0 16 16">
  <path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/>
</svg> {{ post.file }}</a>
						        <img class="rounded mt-3" src="{{ post.image.url }}" width="100%" height="auto">
						      </div>
						  {% endif %}
					    </div>
					  </div>
					</div>

				  <div class="card-footer text-muted">
				  	تاریخ: {{ post.updated_on }}
				  </div>
				  
				</div>
			{% endfor %}
		{% else %}
			<div class="alert alert-danger" role="alert">
			  There is no Posts yet!
			</div>
		{% endif %}
	</div>

		
	</div>
</body>

base/templates/base/files.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static 'base/bash.png' %}">
	<title>{{ type }}</title>
	<meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
</script>

<style>





* {
   box-sizing: border-box;
}
h1 {
   text-align: center;
}
.outer-grid {
   display: flex;
   flex-wrap: wrap;
   padding: 0 4px;
}
.inner-grid {
   flex: 25%;
   max-width: 25%;
   padding: 0 4px;
}
.inner-grid img {
   margin-top: 8px;
   width: 100%;
   padding: 10px;
}
@media screen and (max-width: 800px) {
   .inner-grid {
      flex: 50%;
      max-width: 50%;
   }
}
@media screen and (max-width: 600px) {
   .inner-grid {
      flex: 100%;
      max-width: 100%;
   }
}
</style>

<body class="container mt-3 mb-3">
	<ul class="nav nav-pills nav-fill">
	  <li class="nav-item">
	    <a class="nav-link" aria-current="page" href="{% url 'base:home' %}">Home</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'base:blog' 5 %}">Blog</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'base:profile' %}">Profile</a>
	  </li>

    <li class="nav-item dropdown">
	    <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{{ choice }}</a>

	    <ul class="dropdown-menu">
	      <li><a class="dropdown-item" href="{% url 'base:files' 'all' %}">All Files</a></li>
	      <li><hr class="dropdown-divider"></li>
	      <li><a class="dropdown-item" href="{% url 'base:files' 'musics' %}">Musics</a></li>
	      <li><a class="dropdown-item" href="{% url 'base:files' 'images' %}">Images</a></li>
	      <li><a class="dropdown-item" href="{% url 'base:files' 'files' %}">Files</a></li>
	    </ul>

	  </li>
	</ul>
	<br>
	
	{% if choice == 'All' %}

	<h4>Files</h4>
	<ul class="list-group d-flex">
		{% for file in files %}
			<a class="list-group-item" href="{{ file.file.url }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-files" viewBox="0 0 16 16">
	  <path d="M13 0H6a2 2 0 0 0-2 2 2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 13V4a2 2 0 0 0-2-2H5a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zM3 4a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4z"/>
	</svg> {{ file.name }}</a>
		{% endfor %}
	</ul>
	<br>




		<h4>Musics</h4>
		<div class="row row-cols-1 row-cols-md-3 g-4">
			{% for music in musics %}
				<div class="col">
					<div class="card h-100">
					  <img src="{{ music.image.url }}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h6 class="card-title">{{ music.name }}</h6>
					    {% if music.artist %}
					    <p class="card-text text-muted">{{ music.artist }}</p>
					    {% endif %}
					  </div>
					  <div class="card-footer">
				    	<a class="btn btn-primary btn-sm" href="{{ music.file.url }}">Download</a>
				    	<!--<audio controls class="m-3 d-flex">
						  <source src="{{ music.file.url }}" type="audio/mp3">
						</audio>-->
				    	{% if music.lyrics %}
					    	<button href="#" class="float-end btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal{{ music.id }}">Lyrics</button>

					    	<!-- Modal -->
								<div class="modal fade" id="exampleModal{{ music.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
								  <div class="modal-dialog">
								    <div class="modal-content">
								      <div class="modal-header">
								        <h1 class="modal-title float-center fs-5" id="exampleModalLabel"><h5 class="text-center">{{ music.name }}</h5></h1>
								        <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
								      </div>
								      <div class="modal-body">
								        <div class="p-3">
										    <a style="text-decoration-line: none"  ></a>
										    <p class="text-start">{{ music.lyrics }}</p>
										  </div>
								      </div>
								      
								    </div>
								  </div>
								</div>
						{% endif %}
				      </div>
					</div>
				</div>
				<br>
			{% endfor %}
		</div>
		<br>

		<h4>Images</h4>
		<div class="outer-grid">
			{% for image in images %}
			    <div class="inner-grid border">
			      <img src="{{ image.image.url }}" class="" width="110px" height="auto">
			    </div>
			{% endfor %}
		</div>
	{% endif %}

	{% if choice == 'Musics' %}
		<div class="row row-cols-1 row-cols-md-3 g-4">
			{% for music in musics %}
				<div class="col">
					<div class="card h-100">
					  <img src="{{ music.image.url }}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h6 class="card-title">{{ music.name }}</h6>
					    {% if music.artist %}
					    <p class="card-text text-muted">{{ music.artist }}</p>
					    {% endif %}
					  </div>
					  <div class="card-footer">
				    	<a class="btn btn-primary btn-sm" href="{{ music.file.url }}">Download</a>
				    	<!--<audio controls class="m-3 d-flex">
						  <source src="{{ music.file.url }}" type="audio/mp3">
						</audio>-->
				    	{% if music.lyrics %}
					    	<button href="#" class="float-end btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal{{ music.id }}">Lyrics</button>

					    	<!-- Modal -->
								<div class="modal fade" id="exampleModal{{ music.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
								  <div class="modal-dialog">
								    <div class="modal-content">
								      <div class="modal-header">
								        <h1 class="modal-title float-center fs-5" id="exampleModalLabel"><h5 class="text-center">{{ music.name }}</h5></h1>
								        <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
								      </div>
								      <div class="modal-body">
								        <div class="p-3">
										    <a style="text-decoration-line: none"  ></a>
										    <p class="text-start">{{ music.lyrics }}</p>
										  </div>
								      </div>
								      
								    </div>
								  </div>
								</div>
						{% endif %}
				      </div>
					</div>
				</div>
				<br>
			{% endfor %}
		</div>
	{% endif %}


	{% if choice == 'Images' %}
		{% for image in images %}
			<img src="{{ image.image.url }}" class="img-thumbnail">
		
		{% endfor %}
	{% endif %}


	{% if choice == 'Files' %}
		<ul class="list-group d-flex">
		{% for file in files %}
			<a class="list-group-item" href="{{ file.file.url }}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-files" viewBox="0 0 16 16">
	  <path d="M13 0H6a2 2 0 0 0-2 2 2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 13V4a2 2 0 0 0-2-2H5a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zM3 4a1 1 0 0 1 1-1h7a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4z"/>
	</svg> {{ file.name }}</a>
		{% endfor %}
	</ul>
	{% endif %}







</body>

base/templates/base/home.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static 'base/bash.png' %}">
	<title>{{ type }}</title>
	<meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
</script>


<style type="text/css">
	@media only screen and (min-width: 768px) {
		
	}

	@media only screen and (max-width: 768px) {
		
	}
</style>


<body class="container mt-3 mb-3">
	<ul class="nav nav-pills nav-fill">
	  <li class="nav-item">
	    <a class="nav-link active" aria-current="page" href="{% url 'base:home' %}">Home</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'base:blog' 5 %}">Blog</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'base:profile' %}">Profile</a>
	  </li>
	  <li class="nav-item">
	    <a href="{% url 'base:files' 'all' %}" class="nav-link">Files</a>
	  </li>
	</ul>
	<br>
	<h2 class="text-end">به وبلاگ مقصد نهایی خوش امدید</h2>
	<p class="text-end">این بلاگ برای اشتراک گذاری اهنگ و متن های و اتفاقات روزانه و اموزش های ساده ساخته شده همینو بس ! امیدوارم از وبلاگ لذت ببرید و نهایت استفاده رو بکنید :))</p><br>
	<div class="row">
		<h4 class="text-end text-primary">مطالب پین شده <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pin-fill" viewBox="0 0 16 16">
  <path d="M4.146.146A.5.5 0 0 1 4.5 0h7a.5.5 0 0 1 .5.5c0 .68-.342 1.174-.646 1.479-.126.125-.25.224-.354.298v4.431l.078.048c.203.127.476.314.751.555C12.36 7.775 13 8.527 13 9.5a.5.5 0 0 1-.5.5h-4v4.5c0 .276-.224 1.5-.5 1.5s-.5-1.224-.5-1.5V10h-4a.5.5 0 0 1-.5-.5c0-.973.64-1.725 1.17-2.189A5.921 5.921 0 0 1 5 6.708V2.277a2.77 2.77 0 0 1-.354-.298C4.342 1.674 4 1.179 4 .5a.5.5 0 0 1 .146-.354z"/>
</svg></h6>
		{% if posts %}
			{% for post in posts %}
				<div class="card col rounded m-2">
				  <div class="p-3">
				    <a style="text-decoration-line: none" href="{% url 'base:post_detail' post.slug  %}" data-bs-toggle="modal" data-bs-target="#exampleModal{{ post.id }}"><h5 class="text-end">{{ post.title }}</h5></a>
				    <p class="text-end">{{ post.content | slice:":200" }}</p>
				  </div>


					<!-- Modal -->
					<div class="modal fade" id="exampleModal{{ post.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
					  <div class="modal-dialog">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h1 class="modal-title float-center fs-5" id="exampleModalLabel"><h5 class="text-center">{{ post.title }}</h5></h1>
					        <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
					      </div>
					      <div class="modal-body">
					        <div class="p-3">
							    <a style="text-decoration-line: none" href="{% url 'base:post_detail' post.slug  %}" ></a>
							    <p class="text-end">{{ post.content }}</p>
							  </div>
					      </div>
					      {% if post.image or post.file %}
						      <div class="modal-footer">
						      	<a style="text-decoration-line: none;" href="{{ post.file.url }}"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-folder" viewBox="0 0 16 16">
		}
	<path d="M.54 3.87.5 3a2 2 0 0 1 2-2h3.672a2 2 0 0 1 1.414.586l.828.828A2 2 0 0 0 9.828 3h3.982a2 2 0 0 1 1.992 2.181l-.637 7A2 2 0 0 1 13.174 14H2.826a2 2 0 0 1-1.991-1.819l-.637-7a1.99 1.99 0 0 1 .342-1.31zM2.19 4a1 1 0 0 0-.996 1.09l.637 7a1 1 0 0 0 .995.91h10.348a1 1 0 0 0 .995-.91l.637-7A1 1 0 0 0 13.81 4H2.19zm4.69-1.707A1 1 0 0 0 6.172 2H2.5a1 1 0 0 0-1 .981l.006.139C1.72 3.042 1.95 3 2.19 3h5.396l-.707-.707z"/>
	</svg> {{ post.file }}</a>
						        <img class="rounded mt-3" src="{{ post.image.url }}" width="100%" height="auto">
						      </div>
						  {% endif %}
					    </div>
					  </div>
					</div>

				  
				  
				</div>
			{% endfor %}
		{% else %}
			<div class="alert alert-danger" role="alert">
			  There is no Posts yet!
			</div>
		{% endif %}
		</div>
	</div><br>

	<h4>Musics</h4>
		<div class="row row-cols-1 row-cols-md-3 g-4">
			{% for music in musics %}
				<div class="col">
					<div class="card h-100">
					  <img src="{{ music.image.url }}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h6 class="card-title">{{ music.name }}</h6>
					    <p class="card-text text-muted">{{ music.artist }}</p>
					  </div>
					  <div class="card-footer">
				    	<a class="btn btn-primary btn-sm" href="{{ music.file.url }}">Download</a>
				    	<!--<audio controls class="m-3 d-flex">
						  <source src="{{ music.file.url }}" type="audio/mp3">
						</audio>-->
				    	{% if music.lyrics %}
					    	<button href="#" class="float-end btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal{{ music.id }}">Lyrics</button>

					    	<!-- Modal -->
								<div class="modal fade" id="exampleModal{{ music.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
								  <div class="modal-dialog">
								    <div class="modal-content">
								      <div class="modal-header">
								        <h1 class="modal-title float-center fs-5" id="exampleModalLabel"><h5 class="text-center">{{ music.name }}</h5></h1>
								        <button type="button" class="btn-close float-end" data-bs-dismiss="modal" aria-label="Close"></button>
								      </div>
								      <div class="modal-body">
								        <div class="p-3">
										    <a style="text-decoration-line: none"  ></a>
										    <p class="text-start">{{ music.lyrics }}</p>
										  </div>
								      </div>
								      
								    </div>
								  </div>
								</div>
						{% endif %}
				      </div>
					</div>
				</div>
				<br>
			{% endfor %}
</body>